package com.oyra.todolist.data;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ITEM".
 */
public class Item {

    private Long id;
    /**
     * Not-null value.
     */
    private String text;
    private boolean isComplete;
    private long timestamp;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Item() {
    }

    public Item(Long id) {
        this.id = id;
    }

    public Item(Long id, String text, boolean isComplete, long timestamp) {
        this.id = id;
        this.text = text;
        this.isComplete = isComplete;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getText() {
        return text;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setText(String text) {
        this.text = text;
    }

    public boolean getIsComplete() {
        return isComplete;
    }

    public void setIsComplete(boolean isComplete) {
        this.isComplete = isComplete;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
